from fpdf import FPDF
import datetime

class SystemXReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(0, 86, 179) # MT Blue
        self.cell(0, 10, 'SystemX AI Diagnostic Report', 0, 1, 'C')
        self.set_font('Arial', '', 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f'Generated by SystemX Intelligence Tool | {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf_report(analysis_text, issues, version):
    pdf = SystemXReport()
    pdf.add_page()
    
    # Environment info
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(77, 184, 72) # MT Green
    pdf.cell(0, 10, f'System Environment: SystemX {version}', 0, 1)
    pdf.ln(5)
    
    # AI Content
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, '1. AI Engineering Analysis', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    # Remove Markdown characters before PDF creation
    clean_ai = analysis_text.replace('**', '').replace('#', '').replace('*', '-')
    pdf.multi_cell(0, 6, clean_ai)
    
    pdf.ln(10)
    
    # Issue list
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '2. Detailed Technical Log', 0, 1)
    
    for i, issue in enumerate(issues, 1):
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(0, 8, f' Incident #{i} - Source: {issue["source"]} ({issue["occurrences"]} occurrences)', 0, 1, fill=True)
        pdf.set_font('Arial', 'I', 8)
        pdf.multi_cell(0, 5, f' Location: {issue["location"]}')
        pdf.set_font('Arial', '', 9)
        pdf.multi_cell(0, 5, f' Message: {issue["message"][:400]}')
        pdf.ln(4)
        
    return pdf.output(dest='S')